#Enable checking for new versions of the plugin?
enable-update-checker: true

#Time in seconds until the corpse despawns. Set to -1 for the copse to never despawn.
corpse-time: 120

#Spawn a corpse when the player dies?
on-death: true

#Put the players items into a GUI when they die? Click the the corpse to open the GUI.
looting-inventory: true

#Should the corpse automaticly despawn after it has been looted? (Only has effect is looting-inventory is true!)
despawn-after-looted: true

#Show the username of the player? If you set this to false ' ' will be used for the username. 
#The skin will still show even if you choose not do display the username.
show-tags: true

#This is used to specify what world(s) corpses should spawn when somebody dies.
#Set world to 'all' for every world.
#Use '|' to add multiple worlds.
world: all

#Title of inventory created when you click the corpses head to loot it. 
#%corpse% gets replaced with the corpses name.
#Color codes and unicode characters work, but might be glitchy.
#Minecraft has a 32 character limit on GUI lengths. If your title is more then that you will get a error on the console.
gui-title: "%corpse%'s Items"

#This is the username of the corpse.
#%corpse% gets replaced with the corpses name.
#Color codes and unicode characters work, but might be glitchy.
#Minecraft has a 16 character limit on name lengths. If your title is more then that you will get a error on the console.
username-format: "%corpse%"

#This is the message sent when you finish looting the corpse. Set the message to "none" to disable.
#%corpse% gets replaced with the corpses name.
#Color codes and unicode characters work, but might be glitchy.
finish-looting-message: "&bYou have finished looting %corpse%'s corpse."

#Due to a Minecraft quirk with how the corpses work, the hitboxes were not normal player hitboxes.
#I have now made it so a invisible Cows spawn that covers the whole corpse.
#When you click on the invisible Cow it does the same thing as clicking on the corpse.
#Set to false to use the old glitchy hitboxes.
new-hitboxes: true