#Time in seconds until the corpse despawns. Set to -1 for the copse to never despawn.
corpse-time: 20

#Spawn a corpse when the player dies?
on-death: true

#Put the players items into a gui when they die? CLick the head of the corpse to open the gui.
looting-inventory: false

#Show the username of the player? If you set this to false ' ' will be used for the username. 
#The skin will still show even if you choose not do display the username.
show-tags: true

#Set world to 'all' for every world
world: all

#Title of inventory created when you click the corpses head to loot it. 
#%corpse% gets replaced with the corpses name.
#Color codes and unicode characters work, but might be glitchy.
#Minecraft has a 32 character limit on GUI lengths. If your title is more then that you will get a error on the console.
gui-title: "%corpse%'s Items"

#This is the username of the corpse
#%corpse% gets replaced with the corpses name.
#Color codes and unicode characters work, but might be glitchy.
#Minecraft has a 16 character limit on name lengths. If your title is more then that you will get a error on the console.
username-format: "%corpse%"