main: org.golde.bukkit.corpsereborn.Main
name: CorpseReborn
authors: ["Eric Golde", "Peter Golde", "Virizion"]
website: https://www.spigotmc.org/resources/corpsereborn.29875/
version: 2.9.9
description: "This is a port to 1.7.10-1.12 versions of Spigot from the old Corpse plugin found on Spigot. Thanks to Virizion for letting me take over and manage his project ยง4โค"
load: POSTWORLD
softdepend: [Multiverse-Core, MultiWorld]

commands:
  spawncorpse:
    usage: /<command> [Player]
    description: Spawn a corpse of a player!
    permission: corpses.spawn
    aliases: [spawnc, scorpse, sc]
  removecorpse:
    usage: /<command> [Radius]
    description: Remove a corpse of a player!
    permission: corpses.remove
    aliases: [removec, rcorpse, rc]
  corpsereborn:
    usage: /<command>
    description: Main info about plugin + reload config
    aliases: [cr, corpser, corpse, creborn]
  resendcorpses:
    usage: /<command>
    description: Resend corpses to all players
    permission: corpses.resend
    aliases: [resendc, cresend]
    
permissions:
  corpses.spawn:
    default: op
    description: Permission for /spawncorpse
  corpses.resend:
    default: op
    description: Permission for /resendcorpses
  corpses.remove:
    default: op
    description: Permission for /removecorpse
  corpses.reload:
    default: op
    description: Permission for /corpsereborn reload
  corpses.dump:
    default: op
    description: Permission for /corpsereborn dump