name: CorpseReborn
authors: ["Eric Golde", "Peter Golde", "Virizion"]
website: "https://www.spigotmc.org/resources/corpsereborn.29875/"
version: 2.9
description: "This is a port to 1.7.10-1.11 versions of Spigot from the old Corpse plugin found on Spigot. Thanks to Virizion for letting me take over and manage his project ❤"
main: org.golde.bukkit.corpsereborn.Main
commands:
  spawncorpse:
    usage: /<command> [Player]
    description: Spawn a corpse of a player!
    permission: corpses.spawn
    aliases: [spawnc, scorpse, sc]
  removecorpse:
    usage: /<command> [Radius]
    description: Remove a corpse of a player!
    permission: corpses.remove
    aliases: [removec, rcorpse, rc]
  corpsereload:
    usage: /<command> [Radius]
    description: Reload the config
    permission: corpses.reload
    aliases: [cr, corpser, reloadc]
    
permissions:
  corpses.spawn:
    default: op
    description: Permission for /spawncorpse
  corpses.remove:
    default: op
    description: Permission for /removecorpse
  corpses.reload:
    default: op
    description: Permission for /corpsereload