name: CorpseReborn
author: Eric & Virizion
version: 2.8-pre
description: "This is a port to 1.7.10-1.10 versions of Spigot from the old corpse plugin found here: https://www.spigotmc.org/resources/corpses.1817/ . Credit to Virizion for the original plugin and code! All I did was fix some method and packet changes that occurred when porting this plugin to future versions"
main: org.golde.bukkit.corpsereborn.Main
commands:
  spawncorpse:
    usage: /<command> [Player]
    description: Spawn a corpse of a player!
    permission: corpses.spawn
    aliases: [spawnc, scorpse, sc]
  removecorpse:
    usage: /<command> [Radius]
    description: Remove a corpse of a player!
    permission: corpses.remove
    aliases: [removec, rcorpse, rc]
  corpsereload:
    usage: /<command> [Radius]
    description: Reload the config
    permission: corpses.reload
    aliases: [cr, corpser, reloadc]
    
permissions:
  corpses.spawn:
    default: op
    description: Permission for /spawncorpse
  corpses.remove:
    default: op
    description: Permission for /removecorpse
  corpses.reload:
    default: op
    description: Permission for /corpsereload